server:
  port: 8080
spring:
  application:
    name: "Microservice"
  devtools:
    add-properties: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://localhost:5432/agencia_viajes"
    username: "postgres"
    password: "postgres"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
